name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what
    attributes: { label: What happened?, placeholder: Steps to reproduce… }
    validations: { required: true }
  - type: textarea
    id: logs
    attributes: { label: Logs, render: shell }
