---
name: Auto-Approve & Auto-Merge (bots)
on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
permissions:
  contents: write
  pull-requests: write
jobs:
  approve-and-automerge:
    if: github.actor == 'dependabot[bot]' || startsWith(github.head_ref, 'codex/autofix-')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.graphql(`
                mutation($node_id:ID!) {
                  enablePullRequestAutoMerge(input: {pullRequestId: $node_id, mergeMethod: SQUASH}) {
                    clientMutationId
                  }
                }`,
                { node_id: context.payload.pull_request.node_id }
              );
              core.info("Auto-merge enabled.");
            } catch (e) {
              core.warning(`Cannot enable auto-merge: ${e.message}`);
            }
