---
name: Codex Autofix
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
permissions:
  contents: write
  pull-requests: write
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run ruff & black (no fail on change)
        run: |
          python -m pip install -U ruff black
          ruff check . --fix || true
          black . || true
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: codex/autofix-${{ github.run_id }}
          title: "ci: codex autofix"
          commit-message: "ci: codex autofix"
          body: "Automated formatting/lint fixes."
          labels: autofix
          delete-branch: true
