name: Codex Autofix
on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 13-20 * * 1-5"  # ~18:00–01:00 Asia/Tashkent; подгони по желанию
permissions:
  contents: write
  pull-requests: write
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0 ruff==0.6.9 isort==5.13.2
      - name: Apply fixes
        run: |
          ruff check . --fix || true
          isort . || true
          black . || true
      - name: Quick sanity (log-only)
        run: |
          set +e
          python -m py_compile $(git ls-files "*.py") 2>&1 | tee /tmp/sanity.log || true
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(autofix): ruff/black/isort + sanity"
          branch: "codex/autofix-${{ github.run_id }}"
          title: "Codex Autofix ${{ github.run_id }}"
          body: |
            Авто-PR: форматирование и мелкие правки.
            - ruff --fix
            - isort
            - black
            - py_compile (лог в /tmp/sanity.log)
          labels: autofix, bot
          delete-branch: true
