name: PR Auto-Sync
on:
  schedule:
    - cron: "0 * * * *"   # каждый час
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: List open PRs
        id: list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list --state open --json number,mergeStateStatus,baseRefName \
            -q '.[] | "\(.number)\t\(.mergeStateStatus)\t\(.baseRefName)"' > prs.txt
          echo "PRs:"
          cat prs.txt || true

      - name: Update BEHIND/DIRTY branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          updated=0
          while IFS=$'\t' read -r num state base; do
            [ -z "$num" ] && continue
            if [ "$state" = "BEHIND" ] || [ "$state" = "DIRTY" ]; then
              echo "→ Updating PR #$num vs $base"
              gh api -X PUT "repos/${{ github.repository }}/pulls/$num/update-branch" || true
              updated=$((updated+1))
            fi
          done < prs.txt
          echo "Updated: $updated PR(s)"
