---
name: PR Auto-Sync (Octokit)
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });
            for (const pr of prs) {
              try {
                await github.request(
                  'PUT /repos/{owner}/{repo}/pulls/{pull_number}/update-branch',
                  {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number
                  }
                );
                core.info(`Updated PR #${pr.number}`);
              } catch (e) {
                core.warning(`Skip PR #${pr.number}: ${e.message}`);
              }
            }
